package com.joe.utilities.core.configuration.admin;

import java.io.Serializable;

import com.joe.utilities.core.configuration.admin.domain.IApplicationConfiguration;

public class ApplicationConfiguration implements IApplicationConfiguration, Serializable{

	/**
	 *  UID generated by eclipse
	 */
	private static final long serialVersionUID = 627606516937384380L;
	
	private String code;
	private String categoryCode;
	private String value;
	private String description;
	private boolean editableFlag;

	
	/**
	 * Default constructor (for Hibernate's benefit)
	 */
	public ApplicationConfiguration() {

	}

    /**
     * @param code
     * @param categoryCode
     * @param value
     * @param description
     * @param editableFlag
     */
	public ApplicationConfiguration(String code, String categoryCode, String value, String description, boolean editableFlag) {
		super();
		this.code = code;
		this.categoryCode = categoryCode;
		this.value = value;
		this.description = description;
		this.editableFlag = editableFlag;
	}


    // ****************************************************************************
    // ACCESSORS & MUTATORS
    // ****************************************************************************

	/**
	 * Get the code name for this configuration parameter
	 * @return name
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the code name for this configuration parameter
	 * @param name
	 */
	public void setCode(String code) {
		this.code = code;
	}
	
	/**
	 * Gets the category code for this configuration parameter
	 * @return name
	 */
	public String getCategoryCode(){
		return categoryCode;
	}

	/**
	 * Sets the category code for this configuration parameter
	 * @param category code
	 */
	public void setCategoryCode(String categoryCode){
		this.categoryCode = categoryCode;
	}
	
	/**
	 * Sets the value for this configuration parameter
	 * @return value
	 */
	public String getValue(){
		return value;
	}

	/**
	 * Sets the valuee for this configuration parameter
	 * @param value
	 */
	public void setValue(String value){
		this.value = value;
	}
	
	/**
	 * Get the description for this configuration parameter
	 * @return text description
	 */
	public String getDescription(){
		return description;
	}

	/**
	 * Sets the code description for this configuration parameter
	 * @param text description
	 */
	public void setDescription(String text){
		this.description = text;
	}
	
	/**
	 * 
	 * Gets the Editable flag for this configuration parameter
	 * @return flag
	 */
	public boolean getEditableFlag(){
		return editableFlag;
	}

	/**
	 * Sets the flag to determine if this configuration parameter
	 * is allowed to be edited.
	 * 
	 * @param flag
	 */
	public void setEditableFlag(boolean flag){
		this.editableFlag = flag;
	}

	@Override
	public String toString() {
		String className = this.getClass().getName();
		return className + "(" + super.toString() + "["
			+ "code=" + getCode()
			+ "categoryCode=" + getCategoryCode()
			+ "value=" + getValue()
			+ "description=" + getDescription()
			+ "editableFlag=" + getEditableFlag()
			+ ")";
	}

	
}
