package com.joe.core.domain;

import java.io.Serializable;
import java.util.Date;

import com.joe.client.domain.IUserInfo;

/**
 * UserMaster generated by MyEclipse Persistence Tools
 */

public class UserInfo implements IUserInfo, Serializable {

	// Fields

	private Integer id;

	private String name;

	private Date createDate;

	// Constructors

	/** default constructor */
	public UserInfo() {
		
	}

	public UserInfo(Integer id, String name, Date createDate) {
		super();
		this.id = id;
		this.name = name;
		this.createDate = createDate;
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	

}