package com.joe.client.domain;

import java.util.Date;

/**
 * UserMaster generated by MyEclipse Persistence Tools
 */

public interface IUserInfo{

	

	public Integer getId();

	public void setId(Integer id);

	public String getName();

	public void setName(String name);

	public Date getCreateDate();

	public void setCreateDate(Date createDate);
	
	

}