/* Generated by Together */

package com.joe.utilities.core.util;

public class BusinessRuleException extends Exception {

    /**
     * @param cause
     */
    public BusinessRuleException(Throwable cause) {
        super(cause);
    }

    public BusinessRuleException(){
   		super();
    }

    public BusinessRuleException(String message) {
        super(message);
	}
    public String toString() {
        return "";
    }
}
