USE [master]


IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'alineo')
DROP DATABASE [alineo]


USE [master]


/****** Object:  Database [alineo]    Script Date: 06/17/2010 14:33:42 ******/
CREATE DATABASE [alineo] 

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [alineo].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [alineo] SET ANSI_NULL_DEFAULT OFF

ALTER DATABASE [alineo] SET ANSI_NULLS OFF

ALTER DATABASE [alineo] SET ANSI_PADDING OFF

ALTER DATABASE [alineo] SET ANSI_WARNINGS OFF

ALTER DATABASE [alineo] SET ARITHABORT OFF

ALTER DATABASE [alineo] SET AUTO_CLOSE OFF

ALTER DATABASE [alineo] SET AUTO_CREATE_STATISTICS ON

ALTER DATABASE [alineo] SET AUTO_SHRINK OFF

ALTER DATABASE [alineo] SET AUTO_UPDATE_STATISTICS ON

ALTER DATABASE [alineo] SET CURSOR_CLOSE_ON_COMMIT OFF

ALTER DATABASE [alineo] SET CURSOR_DEFAULT  GLOBAL

ALTER DATABASE [alineo] SET CONCAT_NULL_YIELDS_NULL OFF

ALTER DATABASE [alineo] SET NUMERIC_ROUNDABORT OFF

ALTER DATABASE [alineo] SET QUOTED_IDENTIFIER OFF

ALTER DATABASE [alineo] SET RECURSIVE_TRIGGERS OFF

ALTER DATABASE [alineo] SET  DISABLE_BROKER

ALTER DATABASE [alineo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF

ALTER DATABASE [alineo] SET DATE_CORRELATION_OPTIMIZATION OFF

ALTER DATABASE [alineo] SET TRUSTWORTHY OFF

ALTER DATABASE [alineo] SET ALLOW_SNAPSHOT_ISOLATION OFF

ALTER DATABASE [alineo] SET PARAMETERIZATION SIMPLE

ALTER DATABASE [alineo] SET READ_COMMITTED_SNAPSHOT OFF

ALTER DATABASE [alineo] SET HONOR_BROKER_PRIORITY OFF

ALTER DATABASE [alineo] SET  READ_WRITE

ALTER DATABASE [alineo] SET RECOVERY FULL

ALTER DATABASE [alineo] SET  MULTI_USER

ALTER DATABASE [alineo] SET PAGE_VERIFY CHECKSUM

ALTER DATABASE [alineo] SET DB_CHAINING OFF

EXEC sys.sp_db_vardecimal_storage_format N'alineo', N'ON'

