
IF EXISTS (SELECT * FROM sysobjects   where id =object_id ('CONFIG.FK_APCO_APCC')) ALTER TABLE [CONFIG].[APPL_CONFIG] drop constraint FK_APCO_APCC
IF EXISTS (SELECT * FROM sysobjects   where id =object_id ('CONFIG.PK_APPL_CONFIG')) ALTER TABLE [CONFIG].[APPL_CONFIG] drop constraint PK_APPL_CONFIG
IF   EXISTS (SELECT * FROM sys.tables WHERE object_id   = OBJECT_ID('CONFIG.APPL_CONFIG')) DROP table CONFIG.APPL_CONFIG




/****** Object:  Table [CONFIG].[APPL_CONFIG]    Script Date: 07/12/2010 15:45:57 ******/

CREATE TABLE [CONFIG].[APPL_CONFIG](
	[APPL_CONFIG_CODE] [varchar](255) NOT NULL,
	[APPL_CONFIG_CTGY_CODE] [varchar](20) NOT NULL,
	[APPL_CONFIG_VAL] [varchar](4000) NULL,
	[APPL_CONFIG_TXT] [varchar](500) NOT NULL,
	[EDITABLE_FLAG] [numeric](1, 0) NOT NULL,
 CONSTRAINT [PK_APPL_CONFIG] PRIMARY KEY CLUSTERED 
(
	[APPL_CONFIG_CODE] ASC
)
) 



CREATE UNIQUE NONCLUSTERED INDEX [AK_APPL_CONFIG] ON [CONFIG].[APPL_CONFIG] 
(
	[APPL_CONFIG_TXT]    ASC
)

CREATE NONCLUSTERED INDEX [IF1_APPL_CONFIG] ON [CONFIG].[APPL_CONFIG] 
(
	[APPL_CONFIG_CTGY_CODE] ASC

)  

